### ISSUE TITLE
Question about Gaussian noise.

### ISSUE THREAD

**Issue by wenyuqing** [sled-group/RACER#1]
Hello, thank you very much for your excellent work. I have a question: how exactly do you add the Gaussian noise? What is its magnitude, such as the standard deviation and range? Also, is the intensity of the added noise consistent across different tasks? For some tasks that are very sensitive to interference, larger noise can easily lead to failure—will the noise added for these types of tasks be smaller?

**Comment by YinpeiDai** [comment]
Hi, thanks for asking! The standard deviation of the Gaussian noise is set as the same for many tasks, but also manually selected for some sensitive tasks. We are cleanning the code right now and will publish it later.
